package com.packt.jdeveloper.cookbook.shared.bc.test.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 02 20:32:10 IST 2021
// ---------------------------------------------------------------------
public interface HrAppModule extends ApplicationModule {
    void testSQLProcedure();
}

