package com.packt.jdeveloper.cookbook.shared.bc.utilviews;

import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 04 14:34:48 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApplicationModulePoolStatisticsImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ApplicationModulePoolStatisticsImpl() {
    }
}

