package com.packt.jdeveloper.cookbook.alltest.test.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 02 20:32:10 IST 2021
// ---------------------------------------------------------------------
public interface HRComponentsAppModule extends ApplicationModule {
    void testSQLProcedure();

    void removeEmployeeFromCollection();

    void searchEmployeesUsingAdditionalCriteria();

    int getUserAuthorityLevel();


    String getUserPrincipalName();

    Boolean getApplicationModulePoolStatistics2();


    void prepare();

    void resetEmployees();

    String exportEmployees();

    void createOnPolymorphicVO();


    void changingQueryModeDynamically();

    void findEmployeeForEmpId();

    void executeEmployeeDetailsVOWithBindVar();

    void rowMatchExamples();

    void executeEmployeeVOWithDynamicVC();

    void alterVCAndSaveState();

    void applyVCRowWithConjunction();

    void jointwoVCAndSaveState();
}

