package com.packt.jdeveloper.cookbook.alltest.test.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 02 20:32:10 IST 2021
// ---------------------------------------------------------------------
public interface HRComponentsAppModule extends ApplicationModule {
    void testSQLProcedure();

    void removeEmployeeFromCollection();

    void searchEmployeesUsingAdditionalCriteria();

    int getUserAuthorityLevel();


    String getUserPrincipalName();

    Boolean getApplicationModulePoolStatistics2();

    void adjustCommission(oracle.jbo.domain.Number commissionPctAdjustment);

    void prepare();

    void resetEmployees();

    String exportEmployees();
}

