package com.packt.jdeveloper.cookbook.alltest.test.server.serviceinterface;

import com.packt.jdeveloper.cookbook.alltest.test.HRComponentsAppModuleImpl;
import com.packt.jdeveloper.cookbook.alltest.test.common.serviceinterface.HRComponentsAppModuleService;

import java.lang.reflect.Method;

import java.math.BigDecimal;

import java.util.HashMap;
import java.util.Map;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 04 13:52:50 IST 2021
// ---------------------------------------------------------------------
@Stateless(name = "com.packt.jdeveloper.cookbook.shared.bc.test.common.HRComponentsAppModuleServiceBean",
           mappedName = "HRComponentsAppModuleServiceBean")
@Remote(HRComponentsAppModuleService.class)
@PortableWebService(targetNamespace = "/com/packt/jdeveloper/cookbook/shared/bc/test/common/",
                    serviceName = "HRComponentsAppModuleService", portName = "HRComponentsAppModuleServiceSoapHttpPort",
                    endpointInterface =
                    "com.packt.jdeveloper.cookbook.shared.bc.test.common.serviceinterface.HRComponentsAppModuleService")
@Interceptors({ ServiceContextInterceptor.class })
public class HRComponentsAppModuleServiceImpl extends ServiceImpl implements HRComponentsAppModuleService {
    private static boolean _isInited = false;
    private static final Map _map = new HashMap();

    /**
     * This is the default constructor (do not remove).
     */
    public HRComponentsAppModuleServiceImpl() {
        init();
        setApplicationModuleDefName("com.packt.jdeveloper.cookbook.shared.bc.test.HRComponentsAppModule");
        setConfigurationName("HRComponentsAppModuleService");
    }

    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (HRComponentsAppModuleServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("com/packt/jdeveloper/cookbook/shared/bc/test/common/serviceinterface/",
                                                "HRComponentsAppModuleService.xsd");
                _map.put("adjustCommission",
                         HRComponentsAppModuleImpl.class
                         .getMethod("adjustCommission", new Class[] { oracle.jbo.domain.Number.class }));
                _isInited = true;
            } catch (Throwable t) {
                ADFLogger.createADFLogger(Diagnostic.SERVINT_RT_LOGGER).severe(t);
            }
        }
    }

    /**
     * adjustCommission: generated method. Do not modify.
     */
    public void adjustCommission(BigDecimal commissionPctAdjustment) throws ServiceException {
        invokeCustom((Method) _map.get("adjustCommission"), new Object[] { commissionPctAdjustment },
                     new String[] { null }, false);
    }
}

