<wsdl:definitions
     name="HRComponentsAppModuleService"
     targetNamespace="/com/packt/jdeveloper/cookbook/shared/bc/test/common/"
     xmlns:tns="/com/packt/jdeveloper/cookbook/shared/bc/test/common/"
     xmlns:types="/com/packt/jdeveloper/cookbook/shared/bc/test/common/types/"
     xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:import namespace="http://xmlns.oracle.com/adf/svc/errors/" location="classpath:/META-INF/wsdl/ServiceException.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="/com/packt/jdeveloper/cookbook/shared/bc/test/common/types/" schemaLocation="HRComponentsAppModuleService.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="HRComponentsAppModuleService_adjustCommission">
        <wsdl:part name="parameters" element="types:adjustCommission"/>
    </wsdl:message>
    <wsdl:message name="HRComponentsAppModuleService_adjustCommissionResponse">
        <wsdl:part name="parameters" element="types:adjustCommissionResponse"/>
    </wsdl:message>
    <wsdl:portType name="HRComponentsAppModuleService">
        <wsdl:documentation/>
        <wsdl:operation name="adjustCommission">
            <wsdl:input message="tns:HRComponentsAppModuleService_adjustCommission"/>
            <wsdl:output message="tns:HRComponentsAppModuleService_adjustCommissionResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="HRComponentsAppModuleServiceSoapHttp" type="tns:HRComponentsAppModuleService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="adjustCommission">
            <soap:operation soapAction="/com/packt/jdeveloper/cookbook/shared/bc/test/common/adjustCommission"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="HRComponentsAppModuleService">
        <wsdl:port name="HRComponentsAppModuleServiceSoapHttpPort" binding="tns:HRComponentsAppModuleServiceSoapHttp">
            <soap:address location="http://localhost:7101/Chapter03-Model-context-root/HRComponentsAppModuleService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
