package com.packt.jdeveloper.cookbook.hr.components.caller;


import com.packt.jdeveloper.cookbook.alltest.test.common.serviceinterface.HRComponentsAppModuleService;

import com.packt.jdeveloper.cookbook.alltest.test.server.serviceinterface.HRComponentsAppModuleServiceImpl;

import java.math.BigDecimal;

import oracle.jbo.client.svc.ServiceFactory;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 04 14:02:19 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRComponentsCallerAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HRComponentsCallerAppModuleImpl() {
    }
    
    public void adjustCommission(
    BigDecimal commissionPctAdjustment) {
    // get the service proxy
    HRComponentsAppModuleService service =
    (HRComponentsAppModuleServiceImpl)ServiceFactory
    .getServiceProxy(HRComponentsAppModuleService.NAME);
    // call the adjustCommission() service
    service.adjustCommission(commissionPctAdjustment);
    }
}

