package com.packt.jdeveloper.cookbook.hr.components.model.entities;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 13 09:46:29 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentCollImpl() {
    }
}

