package com.packt.jdeveloper.cookbook.hr.components.model.entities;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 02 15:51:06 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DepartmentId,
        DepartmentName,
        ManagerId,
        LocationId,
        DepartmentManager,
        DepartmentEmployees;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return DepartmentImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return DepartmentImpl.AttributesEnum.firstIndex() + DepartmentImpl.AttributesEnum
                                                                              .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = DepartmentImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int DEPARTMENTMANAGER = AttributesEnum.DepartmentManager.index();
    public static final int DEPARTMENTEMPLOYEES = AttributesEnum.DepartmentEmployees.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentImpl() {
    }

    /**
     * Gets the attribute value for DepartmentId, using the alias name DepartmentId.
     * @return the value of DepartmentId
     */
    public Integer getDepartmentId() {
        return (Integer) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentId.
     * @param value value to set the DepartmentId
     */
    public void setDepartmentId(Integer value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for DepartmentName, using the alias name DepartmentName.
     * @return the value of DepartmentName
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentName.
     * @param value value to set the DepartmentName
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for ManagerId, using the alias name ManagerId.
     * @return the value of ManagerId
     */
    public Integer getManagerId() {
        return (Integer) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManagerId.
     * @param value value to set the ManagerId
     */
    public void setManagerId(Integer value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for LocationId, using the alias name LocationId.
     * @return the value of LocationId
     */
    public BigDecimal getLocationId() {
        return (BigDecimal) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationId.
     * @param value value to set the LocationId
     */
    public void setLocationId(BigDecimal value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * @return the associated entity EmployeesImpl.
     */
    public EmployeeImpl getDepartmentManager() {
        return (EmployeeImpl) getAttributeInternal(DEPARTMENTMANAGER);
    }

    /**
     * Sets <code>value</code> as the associated entity EmployeesImpl.
     */
    public void setDepartmentManager(EmployeeImpl value) {
        setAttributeInternal(DEPARTMENTMANAGER, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDepartmentEmployees() {
        return (RowIterator) getAttributeInternal(DEPARTMENTEMPLOYEES);
    }

    /**
     * @param departmentId key constituent
     * @param departmentName key constituent
     * @param managerId key constituent
     * @param locationId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer departmentId, String departmentName, Integer managerId,
                                       BigDecimal locationId) {
        return new Key(new Object[] { departmentId, departmentName, managerId, locationId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.packt.jdeveloper.cookbook.hr.components.model.entities.Department");
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        // get the department employeess accessor
        RowIterator departmentEmployees = this.getDepartmentEmployees();
        // iterate over all department employees
        while (departmentEmployees.hasNext()) {
        // get the department employee
        EmployeeImpl departmentEmployee =
        (EmployeeImpl)departmentEmployees.next();
        // remove employee
        departmentEmployee.remove();
        }
        super.remove();
    }
}

