package com.packt.jdeveloper.cookbook.hr.components.model.entities;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 15 10:45:56 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeDefImpl() {
    }
}

