package com.packt.jdeveloper.cookbook.hr.components.model.view;

import com.packt.jdeveloper.cookbook.hr.components.model.view.common.Departments;
import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtViewObjectImpl;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaItem;
import oracle.jbo.ViewCriteriaItemValue;
import oracle.jbo.common.ViewCriteriaRowImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 03 15:58:30 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsImpl extends ExtViewObjectImpl implements Departments {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsImpl() {
    }

    @Override
    public String queryLimitedResultsMessage() {
        // TODO Implement this method
        return super.queryLimitedResultsMessage();
    }
    
    
    public void printVC(ViewCriteria vc) {  
         List list = vc.getRows();  
         Iterator iter = list.iterator();  
         while (iter.hasNext()) {  
           ViewCriteriaRowImpl row = (ViewCriteriaRowImpl)iter.next();  
           ViewCriteriaItem[] vcitems = row.getCriteriaItemArray();  
           for (ViewCriteriaItem vcitem : vcitems) {  
             if (vcitem != null) {  
               System.out.println("[ VC Item :" + vcitem.getColumnName() + "Operator " + vcitem.getOperator() + " Value: " + vcitem.getValue() + " ]");  
               if (vcitem.getValueCount() > 1) {  
                 ArrayList<ViewCriteriaItemValue> values = vcitem.getValues();  
                 for (ViewCriteriaItemValue vcItemValue : values)  
                   System.out.println(" [[ Multi select value :" + vcItemValue.getValue() + " ]]");  
               } else if ((vcitem.getValue()) instanceof ViewCriteria) {  
                 System.out.println("<Nested VC is found...>");  
                 //Call recursively   
                 printVC((ViewCriteria)vcitem.getValue());  
               }  
             }  
           }  
         }  
       }  
}

