package com.packt.jdeveloper.cookbook.hr.components.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 02 16:10:58 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeCountRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EmployeeCount;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return EmployeeCountRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return EmployeeCountRowImpl.AttributesEnum.firstIndex() + EmployeeCountRowImpl.AttributesEnum
                                                                                          .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = EmployeeCountRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLOYEECOUNT = AttributesEnum.EmployeeCount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeCountRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute EmployeeCount.
     * @return the EmployeeCount
     */
    public Number getEmployeeCount() {
        return (Number) getAttributeInternal(EMPLOYEECOUNT);
    }
}

