package com.packt.jdeveloper.cookbook.hr.components.model.view;

import com.packt.jdeveloper.cookbook.hr.components.model.entities.EmployeeImpl;

import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtViewRowImpl;

import oracle.adf.share.ADFContext;
import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 03 20:17:17 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesRowImpl extends ExtViewRowImpl {


    public static final int ENTITY_EMPLOYEES = 0;
    public final int ENTITY_EMPLOYEE = 0;
    private static final ADFLogger LOGGER =
        ADFLogger.createADFLogger(EmployeesRowImpl.class);
    private static final int SALES_DEPARTMENT_ID = 80;

    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        // allow employee changes only if the user has the
        // 'AllowEmployeeChanges' role
        return ADFContext.getCurrent().getSecurityContext().isUserInRole("AllowEmployeeChanges")
        ? super.isAttributeUpdateable(i) : false;
        
//        return super.isAttributeUpdateable(i);
    }
    private static final double DEFAULT_COMMISSION = 0.10;

    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        // set the default hire date to today
        this.setHireDate((Date)Date.getCurrentDate());
    }
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CommissionPct,
        DepartmentId,
        Email,
        EmployeeId,
        FirstName,
        HireDate,
        LastName,
        ManagerId,
        PhoneNumber,
        Salary,
        LovAttrib,
        LovSwitcher,
        JobId,
        EmployeesView,
        Departments,
        EmployeeVO,
        DepartmentsLov,
        JobsLov,
        CountriesLov;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMMISSIONPCT = AttributesEnum.CommissionPct.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int HIREDATE = AttributesEnum.HireDate.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int PHONENUMBER = AttributesEnum.PhoneNumber.index();
    public static final int SALARY = AttributesEnum.Salary.index();
    public static final int LOVATTRIB = AttributesEnum.LovAttrib.index();
    public static final int LOVSWITCHER = AttributesEnum.LovSwitcher.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int EMPLOYEESVIEW = AttributesEnum.EmployeesView.index();
    public static final int DEPARTMENTS = AttributesEnum.Departments.index();
    public static final int EMPLOYEEVO = AttributesEnum.EmployeeVO.index();
    public static final int DEPARTMENTSLOV = AttributesEnum.DepartmentsLov.index();
    public static final int JOBSLOV = AttributesEnum.JobsLov.index();
    public static final int COUNTRIESLOV = AttributesEnum.CountriesLov.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesRowImpl() {
    }

    /**
     * Gets Employees entity object.
     * @return the Employees
     */
    public EmployeeImpl getEmployees() {
        return (EmployeeImpl) getEntity(ENTITY_EMPLOYEE);
    }

    /**
     * Gets the attribute value for COMMISSION_PCT using the alias name CommissionPct.
     * @return the COMMISSION_PCT
     */
    public Number getCommissionPct() {
        return (Number) getAttributeInternal(COMMISSIONPCT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMISSION_PCT using the alias name CommissionPct.
     * @param value value to set the COMMISSION_PCT
     */
    public void setCommissionPct(Number value) {
        setAttributeInternal(COMMISSIONPCT, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @return the DEPARTMENT_ID
     */
    public Number getDepartmentId() {
        return (Number) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @param value value to set the DEPARTMENT_ID
     */
    public void setDepartmentId(Number value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @return the EMPLOYEE_ID
     */
    public Number getEmployeeId() {
        return (Number) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for HIRE_DATE using the alias name HireDate.
     * @return the HIRE_DATE
     */
    public Date getHireDate() {
        return (Date) getAttributeInternal(HIREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for HIRE_DATE using the alias name HireDate.
     * @param value value to set the HIRE_DATE
     */
    public void setHireDate(Date value) {
        setAttributeInternal(HIREDATE, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for MANAGER_ID using the alias name ManagerId.
     * @return the MANAGER_ID
     */
    public Number getManagerId() {
        return (Number) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER_ID using the alias name ManagerId.
     * @param value value to set the MANAGER_ID
     */
    public void setManagerId(Number value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     * @return the PHONE_NUMBER
     */
    public String getPhoneNumber() {
        return (String) getAttributeInternal(PHONENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     * @param value value to set the PHONE_NUMBER
     */
    public void setPhoneNumber(String value) {
        setAttributeInternal(PHONENUMBER, value);
    }

    /**
     * Gets the attribute value for SALARY using the alias name Salary.
     * @return the SALARY
     */
    public Number getSalary() {
        return (Number) getAttributeInternal(SALARY);
    }

    /**
     * Sets <code>value</code> as attribute value for SALARY using the alias name Salary.
     * @param value value to set the SALARY
     */
    public void setSalary(Number value) {
        setAttributeInternal(SALARY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LovAttrib.
     * @return the LovAttrib
     */
    public String getLovAttrib() {
        return (String) getAttributeInternal(LOVATTRIB);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LovAttrib.
     * @param value value to set the  LovAttrib
     */
    public void setLovAttrib(String value) {
        setAttributeInternal(LOVATTRIB, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LovSwitcher.
     * @return the LovSwitcher
     */
    public String getLovSwitcher() {
        return (String) getAttributeInternal(LOVSWITCHER);
    }


    /**
     * Gets the attribute value for JOB_ID using the alias name JobId.
     * @return the JOB_ID
     */
    public String getJobId() {
        return (String) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ID using the alias name JobId.
     * @param value value to set the JOB_ID
     */
    public void setJobId(String value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EmployeesView.
     */
    public RowIterator getEmployeesView() {
        return (RowIterator) getAttributeInternal(EMPLOYEESVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Departments.
     */
    public RowIterator getDepartments() {
        return (RowIterator) getAttributeInternal(DEPARTMENTS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EmployeeVO.
     */
    public RowIterator getEmployeeVO() {
        return (RowIterator) getAttributeInternal(EMPLOYEEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DepartmentsLov1.
     */
    public RowSet getDepartmentsLov() {
        return (RowSet) getAttributeInternal(DEPARTMENTSLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> JobsLov.
     */
    public RowSet getJobsLov() {
        return (RowSet) getAttributeInternal(JOBSLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountriesLov1.
     */
    public RowSet getCountriesLov() {
        return (RowSet) getAttributeInternal(COUNTRIESLOV);
    }


}

