package com.packt.jdeveloper.cookbook.hr.components.model.view;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 16 14:08:29 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobsLovRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        JobId,
        JobTitle;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int JOBTITLE = AttributesEnum.JobTitle.index();

    /**
     * This is the default constructor (do not remove).
     */
    public JobsLovRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute JobId.
     * @return the JobId
     */
    public String getJobId() {
        return (String) getAttributeInternal(JOBID);
    }

    /**
     * Gets the attribute value for the calculated attribute JobTitle.
     * @return the JobTitle
     */
    public String getJobTitle() {
        return (String) getAttributeInternal(JOBTITLE);
    }
}

