package com.packt.jdeveloper.cookbook.alltest.test;

import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 02 13:48:57 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRComponentsAppModuleDefImpl extends ApplicationModuleDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HRComponentsAppModuleDefImpl() {
    }
    
    public void testSQLProcedure(){}
}

