package com.packt.jdeveloper.cookbook.alltest.test;

import com.packt.jdeveloper.cookbook.hr.components.model.view.UserInfoImpl;

import com.packt.jdeveloper.cookbook.hr.components.model.view.UserInfoRowImpl;

import oracle.jbo.SQLStmtException;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 07 17:35:04 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserInfoAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UserInfoAppModuleImpl() {
    }

    /**
     * Container's getter for UserInfo.
     * @return UserInfo
     */
    public UserInfoImpl getUserInfo() {
        return (UserInfoImpl) findViewObject("UserInfo");
    }

    public String getFirstName() {
        String firstName = null;
        UserInfoImpl usersInfo = (UserInfoImpl) getUserInfo();
        try {
            usersInfo.executeQuery();
            UserInfoRowImpl userInfo = (UserInfoRowImpl) usersInfo.first();
            if (userInfo != null) {
                firstName = userInfo.getFirstName();
            }
        } catch (SQLStmtException sqlStmtException) {
            System.out.println("sqlerror");
        }
        return firstName;
    }

    public String getLastName() {
        String lastName = null;
        UserInfoImpl usersInfo = (UserInfoImpl) getUserInfo();
        try {
            usersInfo.executeQuery();
            UserInfoRowImpl userInfo = (UserInfoRowImpl) usersInfo.first();
            if (userInfo != null) {
                lastName = userInfo.getLastName();
            }
        } catch (SQLStmtException sqlStmtException) {
            // handle exception
            System.out.println("sqlerror");
        }
        return lastName;
    }

}

