package com.packt.jdeveloper.cookbook.hr.components.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 09 13:02:31 IST 2021
// ---------------------------------------------------------------------
public interface Departments extends ViewObject {
    String queryLimitedResultsMessage();
}

