package com.packt.jdeveloper.cookbook.hr.components.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 03 21:00:37 IST 2021
// ---------------------------------------------------------------------
public interface Employees extends ViewObject {
    void adjustCommission(oracle.jbo.domain.Number commissionPctAdjustment);
}

