package com.packt.jdeveloper.cookbook.hr.components.delete;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 15 16:35:11 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExecutiveSubEmployeeVOViewDefImpl extends ViewDefImpl {
    public ExecutiveSubEmployeeVOViewDefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public ExecutiveSubEmployeeVOViewDefImpl() {
    }
}

