package com.packt.jdeveloper.cookbook.hr.components.delete;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 15 16:35:23 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarketingBaseEmployeeVOViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MarketingBaseEmployeeVOViewImpl() {
    }
}

