package com.packt.jdeveloper.cookbook.hr.components.delete;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 15 16:34:43 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SalesSubEmployeeEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public SalesSubEmployeeEOCollImpl() {
    }
}

